Restart and Quit
MyNameIsNotPa/Atoms-Beats-And-Eats pull request #23
Opened 2017-09-09 00:03 UTC by PaperSlate

Set up Restart and Quit button functionality in the pause menu.

2017-09-09 00:15 UTC, MyNameIsNotPa requested changes
I'll merge once these two comments are addressed.

2017-09-09 00:15 UTC, MyNameIsNotPa commented on Assets/Scripts/View/PauseMenu.cs
> +		currSelected = 0;;
There are two semicolons here

2017-09-09 00:15 UTC, MyNameIsNotPa commented on Assets/Scripts/View/PauseMenu.cs
> +		Application.Quit ();
The quit button is not going to close the application. It will return to the menu once we have made the menu. That's why it wasn't an issue yet.

2017-09-09 04:48 UTC, PaperSlate commented
Removed the application quit and fixed the double semicolon.

2017-09-10 16:34 UTC, MyNameIsNotPa approved these changes

2017-09-10 16:34 UTC, merged